sudo: required
services:
  - docker

before_install:
  - docker build -t vpryshchepa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vpryshchepa/react-test npm test

after_success:
  - docker build -t vpryshchepa/multi-client ./client
  - docker build -t vpryshchepa/multi-nginx ./nginx
  - docker build -t vpryshchepa/multi-server ./server
  - docker build -t vpryshchepa/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  - docker push vpryshchepa/multi-client
  - docker push vpryshchepa/multi-nginx
  - docker push vpryshchepa/multi-server
  - docker push vpryshchepa/multi-worker