sudo: required
services:
  - docker

before_install:
  - docker build -t nfrowner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nfrowner/react-test npm test

after_success:
  - docker build -t nfrowner/multi-client ./client
  - docker build -t nfrowner/multi-nginx ./nginx
  - docker build -t nfrowner/multi-server ./server
  - docker build -t nfrowner/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  - docker push nfrowner/multi-client
  - docker push nfrowner/multi-nginx
  - docker push nfrowner/multi-server
  - docker push nfrowner/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-487137014672'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY